server :
  port : 8081
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/whatap?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true # 새로 추가된 옵션 schema 가 없는 경우 생성
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE

#logging:
#  level:
#    root: info
#    com.zaxxer.hikari.HikariConfig: debug
#    org.hibernate.SQL: debug
#    hibernate.type.descriptor.sql.BasicBinder: trace